### ISSUE TITLE
Provide extension build here on GitHub similar to TWP

### ISSUE THREAD

**Issue by ylluminate** [OrionReed/dom3d#1]
Fwiw, when you get to the point of building this, it would be nice to provide builds similar to this: https://github.com/FilipePS/Traduzir-paginas-web

So that Chromium Web Store (https://github.com/NeverDecaf/chromium-web-store) can manage these for those of us who use Chromium ungoogled.

**Comment by OrionReed** [comment]
This sounds like a good idea. I'm happy to set that up. I will come back to this issue once Chrome is working.

**Comment by OrionReed** [comment]
Does [this](https://avoidthehack.com/manually-install-extensions-ungoogled-chromium) approach work for de-googled Chromium extensions? Or is there something I can do to make installation easier?

I've submitted the extension to the Chrome web store.

**Comment by OrionReed** [comment]
Great, closing for now, feel free to reopen if there's more that can/should be done here.
