### ISSUE TITLE
Publish on addon stores

### ISSUE THREAD

**Issue by Mte90** [OrionReed/dom3d#15]
You can use github ci for that:

* https://github.com/wdzeng/firefox-addon
* https://github.com/wdzeng/chrome-extension

**Comment by Mte90** [comment]
maybe duplicate of #1?

**Comment by OrionReed** [comment]
I have submitted [v0.0.2](https://github.com/OrionReed/dom3d/releases/tag/v0.0.2) to the Chrome and Firefox extension stores. Once those are up it should be possible to automate future release (which will be needed before anyone really would want to use this lil tool)

**Comment by OrionReed** [comment]
The extension has now been submitted/approved for Firefox and Chrome. Both versions are a little out of date, but they're up!
- [Firefox add-on](https://addons.mozilla.org/en-US/firefox/addon/dom3d/)
- [Chrome extension](https://chromewebstore.google.com/detail/dom3d/lhdhfmkagpnfjjdgbionncpiolioknpj)

Marking closed for now, though I would love to have it on Safari too (and mobile) but not sure how to do that yet.
