### ISSUE TITLE
Build for Chrome

### ISSUE THREAD

**Issue by eshiofune** [OrionReed/dom3d#2]
I'd like to work on creating a Chrome extension for this;

- are you or is there anyone already working on it ?
- could you add a licence or help clarify how this project can be used and built on ?

@OrionReed

**Comment by OrionReed** [comment]
That would be great! I'd love to get this working on Chrome, but not sure how exactly. The 3D DOM view works fine but I'm unsure how to setup cross-browser compatibility in this project or debug it. I also just added a GNU license file, so do whatever you want with this repo as long as it remains free for others to take advantage of.

If you are able to get this working as a Chrome extension, feel free to submit a PR! Hopefully we can merge Chrome/Safari/other setups into a shared repo with minimal differences.

**Comment by OrionReed** [comment]
Closed via #4
