### ISSUE TITLE
manifest.json not showing as available to install on Chromium via "Load unpacked"

### ISSUE THREAD

**Issue by ylluminate** [OrionReed/dom3d#6]
Just wanted to document this here as I'm not yet sure why: `dom3d/dist/chrome/manifest.json` is not presenting as valid when using `Load unpacked` and with `Developer mode` toggled on:

![example](https://p153.p0.n0.cdn.zight.com/items/GGud1RQy/73d109e8-6ba9-4704-b6f1-4170acc15d29.png?v=f5003976bafba5abe00bdbe69455a5eb)

**Comment by OrionReed** [comment]
You should be able to load the folder directly. The readme has been updated to reflect this.

Are you able to select & the folder?
